env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': off
settings:
  react:
    version: detect
  'import/resolver':
    alias:
      map:
        - ['@', './']
        - ['@main', './main']
        - ['@renderer', './renderer']
      extensions:
        - .ts
        - .tsx
        - .json
