export enum CONSTS {
  POLLING = 'POLLING', // 轮询
  WEIGHTS = 'WEIGHTS', // 权重
  RANDOM = 'RANDOM', // 随机
  SPECIFY = 'SPECIFY', // 声明绑定
  WEIGHTS_POLLING = 'WEIGHTS_POLLING', // 权重轮询
  WEIGHTS_RANDOM = 'WEIGHTS_RANDOM', // 权重随机
  MINIMUM_CONNECTION = 'MINIMUM_CONNECTION', // 最小连接数
  WEIGHTS_MINIMUM_CONNECTION = 'WEIGHTS_MINIMUM_CONNECTION', // 权重最小连接数
}

export default CONSTS;
