import CONSTS from '../consts';
import POLLING from './POLLING';
import RANDOM from './RANDOM';
import WEIGHTS from './WEIGHTS';
import SPECIFY from './SPECIFY';
import WEIGHTS_RANDOM from './WEIGHTS_RANDOM';
import WEIGHTS_POLLING from './WEIGHTS_POLLING';
import MINIMUM_CONNECTION from './MINIMUM_CONNECTION';
import WEIGHTS_MINIMUM_CONNECTION from './WEIGHTS_MINIMUM_CONNECTION';

export default {
  [CONSTS.POLLING]: POLLING,
  [CONSTS.WEIGHTS]: WEIGHTS,
  [CONSTS.RANDOM]: RANDOM,
  [CONSTS.SPECIFY]: SPECIFY,
  [CONSTS.MINIMUM_CONNECTION]: MINIMUM_CONNECTION,
  [CONSTS.WEIGHTS_POLLING]: WEIGHTS_POLLING,
  [CONSTS.WEIGHTS_RANDOM]: WEIGHTS_RANDOM,
  [CONSTS.WEIGHTS_MINIMUM_CONNECTION]: WEIGHTS_MINIMUM_CONNECTION,
};
