env:
  browser: true
  node: true
  es2021: true
extends:
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
  'import/resolver':
    alias:
      map:
        - ['@', '../..']
        - ['@main', '../main']
        - ['@common', '../common']
        - ['@renderer', '.']
      extensions:
        - .ts
        - .tsx
        - .json
